
{{ if .Values.scheduler.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "thirdeye.scheduler.fullname" . }}
  labels:
    app: {{ include "thirdeye.name" . }}
    chart: {{ include "thirdeye.chart" . }}
    component: {{ .Values.scheduler.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.scheduler.serviceType }}
  ports:
    # [pod_name].[service_name].[namespace].svc.cluster.local
    - name: http
      protocol: TCP
      port: {{ .Values.scheduler.port }}
      targetPort: {{ .Values.scheduler.port }}
    - name: admin
      protocol: TCP
      port: 8081
      targetPort: 8081
    {{- if .Values.scheduler.tls.enabled }}
    - name: https
      protocol: TCP
      port: {{ .Values.scheduler.tls.port }}
      targetPort: {{ .Values.scheduler.tls.port }}
    {{- end }}
  selector:
    app: {{ include "thirdeye.name" . }}
    release: {{ .Release.Name }}
    component: {{ .Values.scheduler.name }}
{{ end }}
