#
# Copyright 2024 StarTree Inc
#
# Licensed under the StarTree Community License (the "License"); you may not use
# this file except in compliance with the License. You may obtain a copy of the
# License at http://www.startree.ai/legal/startree-community-license
#
# Unless required by applicable law or agreed to in writing, software distributed under the
# License is distributed on an "AS IS" BASIS, WITHOUT * WARRANTIES OF ANY KIND,
# either express or implied.
# See the License for the specific language governing permissions and limitations under
# the License.
#

{{ if and .Values.traefik.enabled .Values.tls.enabled .Values.tls.v2 .Values.tls.traefik.serversTransport.create -}}
apiVersion: {{ ternary "traefik.io/v1alpha1" "traefik.containo.us/v1alpha1" .Value.starforge.enabled }}
kind: ServersTransport
metadata:
  name: {{ .Values.tls.traefik.serversTransport.name }}
  namespace: {{ .Release.Namespace }}
spec:
  insecureSkipVerify: {{ default false .Values.tls.traefik.serversTransport.skipVerify }}
  rootCAsSecrets:
    - {{ .Values.tls.rootCaSecretName }}
  serverName: '{{ .Release.Namespace }}.svc'

{{- end }}
