######################################################
# ThirdEye Coordinator default config
######################################################

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin

  connector:
    type: http
    port: 8080
    idleTimeout: 620s
#   SSL connector is disabled since APP Engine only allows exposing a single port.
#   A sample keystore and password is added so that this can be tested locally.
#   However, the settings currently don't work on GAE
#    - type: https
#      port: 8443
#      keyStorePath: conf/keystore.jks
#      keyStorePassword: password

logging:
  level: INFO
  loggers:
    org.apache.pinot.thirdeye: DEBUG
    org.apache.zookeeper: WARN

auth:
  jwt:
    enabled: true
    signingKey: 9sz834jghfdglsE4sYNT4zfrU4JwLARcUhxd2
    issuer: thirdeye
    accessTokenExpiry: P1D # Duration: 1 day. Format: https://en.wikipedia.org/wiki/ISO_8601

database:
  # Assuming a local MySQL server running on the default port 3306
  url: jdbc:mysql://localhost/thirdeye_test?autoReconnect=true
  user: uthirdeye
  password: pass
  driver: com.mysql.jdbc.Driver

swagger:
  # Enable/Disable the swagger resource. Helps in API documentation. Should be true by default
  enabled: true

  # package to scan for jersey resources
  resourcePackage: org.apache.pinot.thirdeye.resources
