---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: repo.startreedata.io/external-docker-registry/ci-java-11
    tag: latest

caches:
  - path: src/m2

inputs:
- name: src
- name: ci-src

outputs:
- name: src
- name: version

params:
  MVN_REPOSITORY_USERNAME: ((artifactory-username))
  MVN_REPOSITORY_PASSWORD: ((artifactory-password))

run:
  path: ci-src/.concourse/tasks/build-thirdeye/build-thirdeye.sh
