on:
  # for debugging purpose
  workflow_dispatch:

name: Slack Notification DEBUG

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://cdn.iconscout.com/icon/free/png-64/free-github-3691248-3073768.png?f=webp
          SLACK_MESSAGE: 'Test Cyril message @cyril'
          SLACK_TITLE: Test Post Title
          SLACK_LINK_NAMES: true
          SLACK_USERNAME: githubAction
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  slackNotificationFail:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: fail
        run: exit 1
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://cdn.iconscout.com/icon/free/png-64/free-github-3691248-3073768.png?f=webp
          SLACK_MESSAGE: 'Test Cyril message @cyril'
          SLACK_TITLE: Test Post Title
          SLACK_LINK_NAMES: true
          SLACK_USERNAME: githubAction
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
