# Workflow to triage pull requests and test/build ThirdEye UI project
name: ThirdEye UI PR Workflow

on:
    pull_request:
        branches: master
        paths: thirdeye-ui/**

jobs:
    thirdeye-ui-pr-checks:
        name: PR Checks
        runs-on: ubuntu-latest
        env:
          NPM_CONFIG__AUTH: ${{ secrets.NPM_ARTIFACTORY_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Read Node Version
              run: echo ::set-output name=NVMRC::$(cat thirdeye-ui/.nvmrc)
              id: nvmrc

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: "${{ steps.nvmrc.outputs.NVMRC }}"

            - name: Install Packages
              working-directory: thirdeye-ui
              run: npm ci

            - name: ESLint
              working-directory: thirdeye-ui
              run: npm run eslint-check

            - name: stylelint
              working-directory: thirdeye-ui
              run: npm run stylelint-check

            - name: Prettier
              working-directory: thirdeye-ui
              run: npm run prettier-check

            - name: Build
              working-directory: thirdeye-ui
              run: npm run build

            - name: Test
              working-directory: thirdeye-ui
              run: npm run test
